Add backfill TTL config variable
googleforgames/open-match pull request #1326
Opened 2021-01-04 13:26 UTC by hsorellana

**What this PR does / Why we need it**:
This PR adds a new variable in Helm charts for configuring the timeout for Backfill TTL

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This PR should be merged after #1325 is merged and all resolving all conflicts, if any.

2021-01-07 21:08 UTC, Laremere commented
I prefer the timeout being a fraction of the ticket pending timeout, as it is requires less configuration, and it removes a possible misconfiguration causing bugs.  Is there a compelling reason to add this?

2021-01-08 19:04 UTC, hsorellana commented
as i understood it, this variable goes in replacement because, right now, it is used another variable for this use case, which wasn't meant to be, in the first place

2021-01-12 19:45 UTC, hsorellana commented
@Laremere i was thinking about adding the `backfillTimeToLive` variable in a way that it's use like this:

```go
func getBackfillReleaseTimeout(cfg config.View) time.Duration {
	return cfg.GetDuration("pendingReleaseTimeout") * cfg.GetFloat64("backfillTimeToLive")
}
```

so that way, in either values.yaml files, can be defined how much percentage of `pendingReleaseTimeout` should be applied to `backfillTimeToLive`, but everything configurable can be source of bugs.

What do you think about this??

2021-01-12 20:03 UTC, aLekSer commented
@hsorellana there might be `backfillTTLPortion` parameter which is in between `(0; 80%)` interval. If something bigger than this  you can default it to `80%` with warning message, that one of parameters was ignored.

2021-01-12 20:05 UTC, hsorellana commented
@aLekSer nice, i like that approach

2021-01-12 20:06 UTC, Laremere commented
Sorry - still don't see the need for this variable?

It's okay if the ticket pending timeout is used for this as well - they're both related to how long OM should wait before giving up on game servers.  Perhaps we should document the config file a bit better, but other than that I don't see any value in having this as a configuration option - when would someone ever want to change it from the default?

2021-01-12 20:07 UTC, aLekSer commented
This parameter was requested by @scosgrave Sean and the team.

2021-01-13 16:55 UTC, aLekSer commented on internal/statestore/ticket_test.go
> +	cfg.Set("backfillTimeToLive", "800ms")
@hsorellana I thought you would change this `800ms` time to some per cent value and rename this `backfillTimeToLive` to something like `backfillTTL` .

2021-01-13 16:57 UTC, aLekSer requested changes
Changes in this PR are inconsistent

2021-01-13 17:35 UTC, aLekSer commented
This should hold: `AcknowledgeBackfill time < cleanupBackfillTTL < pendingRelease timeout`.
Otherwise backfill would be expired, or for the second we have some regular tickets associated but already returned to the pool of available tickets.

2021-01-13 18:53 UTC, closed without merging

2021-01-13 20:26 UTC, scosgrave commented
> This parameter was requested by @scosgrave Sean and the team.

I think we requested this because we did not know tickets would be released from the backfill when pendingRelease timeout happened. Having seen the work you have done, and the discussion here, I agree that backfillTTL should not be a independent config setting. We should make it a percentage of the pendingRelease timeout, and make sure we document that there is a relationship between the two. In addition, we should make it easy for those running Open Match to determine how often their game servers should acknowledge backfills. Maybe we should print out the backfillTTL at startup?